
local ModuleLoader = require("modules/exp_util/module_loader")
local module_loader, require = ModuleLoader.closure()

--- Command Extensions
require("modules/exp_scenario/commands/_authorities")
require("modules/exp_scenario/commands/_rcon")
require("modules/exp_scenario/commands/_types")

--- Commands
require("modules/exp_scenario/commands/admin_chat")
require("modules/exp_scenario/commands/artillery")
require("modules/exp_scenario/commands/bot_queue")
require("modules/exp_scenario/commands/cheat")
require("modules/exp_scenario/commands/clear_inventory")
require("modules/exp_scenario/commands/connect")
require("modules/exp_scenario/commands/debug")
require("modules/exp_scenario/commands/enemy")
require("modules/exp_scenario/commands/home")
require("modules/exp_scenario/commands/jail")
require("modules/exp_scenario/commands/kill")
require("modules/exp_scenario/commands/lawnmower")
require("modules/exp_scenario/commands/locate")
require("modules/exp_scenario/commands/me")
require("modules/exp_scenario/commands/protected_entities")
require("modules/exp_scenario/commands/protected_tags")
require("modules/exp_scenario/commands/rainbow")
require("modules/exp_scenario/commands/ratio")
require("modules/exp_scenario/commands/repair")
require("modules/exp_scenario/commands/reports")
require("modules/exp_scenario/commands/research")
require("modules/exp_scenario/commands/roles")
require("modules/exp_scenario/commands/search")
require("modules/exp_scenario/commands/spectate")
require("modules/exp_scenario/commands/surface")
require("modules/exp_scenario/commands/teleport")
require("modules/exp_scenario/commands/trains")
require("modules/exp_scenario/commands/vlayer")
require("modules/exp_scenario/commands/warnings")
require("modules/exp_scenario/commands/waterfill")

--- Control
require("modules/exp_scenario/control/afk_kick")
require("modules/exp_scenario/control/bonus")
require("modules/exp_scenario/control/chat_auto_reply")
require("modules/exp_scenario/control/chat_popup")
require("modules/exp_scenario/control/custom_start")
require("modules/exp_scenario/control/damage_popups")
require("modules/exp_scenario/control/death_markers")
require("modules/exp_scenario/control/deconstruction_log")
require("modules/exp_scenario/control/degrading_tiles")
require("modules/exp_scenario/control/discord_alerts")
require("modules/exp_scenario/control/extra_logging")
require("modules/exp_scenario/control/fast_deconstruction")
require("modules/exp_scenario/control/help_bubbles")
require("modules/exp_scenario/control/inserter_pickup")
require("modules/exp_scenario/control/inventory_clear")
require("modules/exp_scenario/control/mine_depletion")
require("modules/exp_scenario/control/nuke_protection")
require("modules/exp_scenario/control/pollution_grading")
require("modules/exp_scenario/control/protection_jail")
require("modules/exp_scenario/control/report_jail")
require("modules/exp_scenario/control/research")
require("modules/exp_scenario/control/spawn_area")
require("modules/exp_scenario/control/station_auto_name")

--- Guis
require("modules/exp_scenario/gui/autofill")
require("modules/exp_scenario/gui/elements")
require("modules/exp_scenario/gui/landfill_blueprint")
require("modules/exp_scenario/gui/module_inserter")
require("modules/exp_scenario/gui/player_bonus")
require("modules/exp_scenario/gui/player_stats")
require("modules/exp_scenario/gui/production_stats")
require("modules/exp_scenario/gui/quick_actions")
require("modules/exp_scenario/gui/research_milestones")
require("modules/exp_scenario/gui/science_production")
require("modules/exp_scenario/gui/surveillance")

log("[ExpScenario] Loading modules...")
module_loader:load_modules()
module_loader:output_counts(function(msg) log("[ExpScenario] Loaded " .. msg) end)

return module_loader
